stages:
  data_download:
    cmd: python mlops/download_csv.py
    deps:
      - mlops/download_csv.py
    params:
      - data_download.url
    outs: []
    
  create_datasets:
    cmd: python mlops/create_datasets.py
    deps:
      - mlops/create_datasets.py
      - data/
    params:
      - create_datasets.test_size
      - create_datasets.random_state
    outs: []

  data_transform:
    cmd: python mlops/data_preprocessing.py
    deps:
      - mlops/data_preprocessing.py
      - data/
    outs: []

  feature_engineering:
    cmd: python mlops/feature_engineering.py
    params:
      - feature_engineering
    deps:
      - mlops/feature_engineering.py
      - data/
    outs: []

  model_building:
    cmd: python mlops/train.py
    deps:
      - mlops/train.py
      - data/
    params:
      - train.gbc_n_estimators
    outs:
      - models/gbc_model.pkl:
          persist: true

  model_evaluation:
    cmd: python mlops/evaluation.py
    deps:
      - mlops/evaluation.py
      - models/gbc_model.pkl
    metrics:
      - reports/metrics_gbc.json
