stages:
  data_download:
    cmd: python mlops/download_csv.py
    deps:
      - mlops/download_csv.py
    outs:
      - data/external:
          persist: true      

  data_preprocess:
    cmd: python mlops/create_datasets.py
    deps:
      - mlops/create_datasets.py
      - data/external
    outs:
      - data/raw:
          persist: true    

  data_transform:
    cmd: python mlops/data_preprocessing.py
    deps:
      - mlops/data_preprocessing.py
      - data/raw           
    outs:
      - data/processed:
          persist: true      

  feature_engineering:
    cmd: python mlops/feature_engineering.py
    deps:
      - mlops/feature_engineering.py
      - data/processed
    outs:
      - data/interim
  model_building:
    cmd: python mlops/train.py
    deps:
      - mlops/train.py
      - data/interim
    outs:
      - models/gbc_model.pkl:
          persist: true

  model_evaluation:
    cmd: python mlops/evaluation.py
    deps:
      - mlops/evaluation.py
      - models/gbc_model.pkl
