data_download:
  url: https://raw.githubusercontent.com/campusx-official/jupyter-masterclass/main/tweet_emotions.csv

# nothing to put right now
data_preprocessing: ~

feature_engineering:
  cv_max_features: 7500

create_datasets:
  test_size: 0.2
  random_state: 47

train:
  gbc_n_estimators: 64

