data_download:
  url: https://raw.githubusercontent.com/campusx-official/jupyter-masterclass/main/tweet_emotions.csv

# nothing to put right now
data_ingestion: ~

feature_engineering:
  cv_max_features: 6000

create_datasets:
  test_size: 0.2
  random_state: 42

train:
  gbc_n_estimators: 50

